spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/makeamatch
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  tomcat:
    max-http-response-header-size: 8KB
  max-http-request-header-size: 8KB
